# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ProjectAccumulation' do

pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage', '~> 3.7.3'

end


#target 'ProjectAccumulationTests' do
#end

